package com.schooloss.fullnative.core;
import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import org.json.JSONObject;import java.util.concurrent.*;
public abstract class BaseActivity extends AppCompatActivity {
 protected ApiClient api; protected final ExecutorService io=Executors.newSingleThreadExecutor();
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xFFF8FAFF);getWindow().setNavigationBarColor(0xFFFFFFFF);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);api=new ApiClient(this);}
 @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
 protected JSONObject session(){return api.store().session();}
 protected String message(Throwable e){String m=e==null?null:e.getMessage();return m==null||m.trim().isEmpty()?"SchoolOS could not complete this request.":m;}
 protected void loading(String title,String sub){LinearLayout p=Ui.v(this);p.setGravity(Gravity.CENTER);p.setPadding(Ui.dp(this,28),Ui.dp(this,28),Ui.dp(this,28),Ui.dp(this,28));p.setBackgroundColor(Constants.BG);TextView mark=Ui.text(this,"S",24,0xFFFFFFFF,true);mark.setGravity(Gravity.CENTER);mark.setBackground(Ui.round(Constants.BLUE,Ui.dp(this,18)));p.addView(mark,new LinearLayout.LayoutParams(Ui.dp(this,58),Ui.dp(this,58)));p.addView(Ui.gap(this,16));TextView h=Ui.text(this,title,21,Constants.TEXT,true);h.setGravity(Gravity.CENTER);p.addView(h);TextView s=Ui.text(this,sub,11,Constants.MUTED,false);s.setGravity(Gravity.CENTER);s.setPadding(0,Ui.dp(this,7),0,Ui.dp(this,14));p.addView(s);p.addView(new ProgressBar(this));setContentView(p);}
 protected void error(String title,Throwable e,Runnable retry){LinearLayout p=Ui.v(this);p.setGravity(Gravity.CENTER);p.setPadding(Ui.dp(this,22),Ui.dp(this,22),Ui.dp(this,22),Ui.dp(this,22));p.setBackgroundColor(Constants.BG);com.google.android.material.card.MaterialCardView c=Ui.card(this);LinearLayout in=Ui.v(this);in.setPadding(Ui.dp(this,18),Ui.dp(this,18),Ui.dp(this,18),Ui.dp(this,18));in.addView(Ui.text(this,title,20,Constants.TEXT,true));in.addView(Ui.gap(this,7));in.addView(Ui.text(this,message(e),12,Constants.MUTED,false));in.addView(Ui.gap(this,12));com.google.android.material.button.MaterialButton b=Ui.button(this,"Try Again",Constants.BLUE,0xFFFFFFFF);b.setOnClickListener(v->retry.run());in.addView(b);c.addView(in);p.addView(c,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));setContentView(p);}
}