package com.schooloss.fullnative.core;
import java.util.*;
public final class FeatureRegistry {
 private FeatureRegistry(){}
 private static void add(List<String[]>l,String k,String n,String g){l.add(new String[]{k,n,g});}
 public static List<String[]> forRole(String role){List<String[]> x=new ArrayList<>();
  if("admin".equals(role)){add(x,"admissions","Admissions","People");add(x,"students","Students","People");add(x,"guardians","Guardians","People");add(x,"staff","Staff","People");add(x,"classes","Classes & Sections","Academics");add(x,"subjects","Subjects","Academics");add(x,"rooms","Rooms","Academics");add(x,"attendance","Attendance","Academics");add(x,"timetable","Timetable","Academics");add(x,"assignments","Assignments","Teaching");add(x,"lesson_plans","Lesson Plans","Teaching");add(x,"learning_materials","Learning Materials","Teaching");add(x,"study_from_home","Study From Home","Teaching");add(x,"exams","Exams","Assessment");add(x,"marks","Marks","Assessment");add(x,"results","Results & Reports","Assessment");add(x,"fees","Fees","Finance");add(x,"fee_invoices","Invoices & Payments","Finance");add(x,"fee_installments","Installments","Finance");add(x,"fee_reminders","Fee Reminders","Finance");add(x,"messages","Messages","Communication");add(x,"notifications","Notifications","Communication");add(x,"calendar","School Calendar","Communication");add(x,"requests","Requests & Approvals","Operations");add(x,"transport","Transport","Operations");add(x,"gallery","Gallery","Operations");add(x,"portal_accounts","Portal Accounts","Administration");add(x,"reports","Reports & Analytics","Administration");add(x,"audit","Audit Logs","Administration");add(x,"settings","Settings","Administration");add(x,"billing","Subscription & Billing","Administration");}
  else if("teacher".equals(role)){add(x,"attendance","Attendance","Today");add(x,"timetable","Schedule","Today");add(x,"students","Students","Today");add(x,"assignments","Assignments","Teaching");add(x,"lesson_plans","Lesson Plans","Teaching");add(x,"learning_materials","Learning Materials","Teaching");add(x,"study_from_home","Study From Home","Teaching");add(x,"exams","Exams","Assessment");add(x,"marks","Marks","Assessment");add(x,"results","Results","Assessment");add(x,"messages","Messages","Communication");add(x,"notifications","Updates","Communication");add(x,"calendar","Calendar","Communication");add(x,"requests","Requests","Operations");add(x,"gallery","Gallery","School");add(x,"transport","Transport","School");}
  else if("parent".equals(role)){add(x,"students","My Child","Child");add(x,"attendance","Attendance","Child");add(x,"timetable","Timetable","Child");add(x,"assignments","Assignments","Learning");add(x,"study_from_home","Study From Home","Learning");add(x,"results","Results & Reports","Learning");add(x,"fees","Fees & Payments","Finance");add(x,"messages","Messages","Communication");add(x,"notifications","Updates","Communication");add(x,"calendar","Calendar","School");add(x,"transport","Transport","School");add(x,"gallery","Gallery","School");add(x,"requests","Requests","School");}
  else{add(x,"timetable","Schedule","Today");add(x,"attendance","Attendance","Today");add(x,"assignments","Assignments","Learning");add(x,"learning_materials","Learning Materials","Learning");add(x,"study_from_home","Study From Home","Learning");add(x,"results","Results & Reports","Learning");add(x,"fees","Fees","Finance");add(x,"messages","Messages","Communication");add(x,"notifications","Updates","Communication");add(x,"calendar","Calendar","School");add(x,"transport","Transport","School");add(x,"gallery","Gallery","School");}
  return x;}
}