package com.schooloss.fullnative.feature.home;
import android.content.*;import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.recyclerview.widget.*;import com.schooloss.fullnative.core.*;import com.schooloss.fullnative.feature.auth.LoginActivity;import org.json.*;import java.util.*;
public final class HomeActivity extends BaseActivity {
 private JSONObject home;
 @Override protected void onCreate(Bundle b){super.onCreate(b);loading("Loading SchoolOS","Building your native workspace…");load();}
 private void load(){io.execute(()->{try{JSONObject r=api.get("home");JSONObject s=r.optJSONObject("session");if(s!=null)api.store().session(s);home=r.optJSONObject("data");runOnUiThread(this::render);}catch(Exception e){runOnUiThread(()->error("Could not load SchoolOS",e,this::load));}});}
 private void render(){JSONObject s=session();String role=s.optString("role","admin");JSONObject school=s.optJSONObject("school");LinearLayout root=Ui.v(this);root.setBackgroundColor(Constants.BG);LinearLayout head=Ui.h(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(Ui.dp(this,16),Ui.dp(this,12),Ui.dp(this,16),Ui.dp(this,12));head.setBackgroundColor(0xFFFFFFFF);TextView logo=Ui.text(this,"S",19,0xFFFFFFFF,true);logo.setGravity(Gravity.CENTER);logo.setBackground(Ui.round(Constants.BLUE,Ui.dp(this,13)));head.addView(logo,new LinearLayout.LayoutParams(Ui.dp(this,42),Ui.dp(this,42)));LinearLayout hc=Ui.v(this);hc.setPadding(Ui.dp(this,10),0,0,0);hc.addView(Ui.text(this,school==null?"SchoolOS":school.optString("name","SchoolOS"),17,Constants.TEXT,true));hc.addView(Ui.text(this,Ui.pretty(role)+" workspace",10,Constants.MUTED,false));head.addView(hc,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));TextView profile=Ui.text(this,"ME",10,Constants.BLUE,true);profile.setGravity(Gravity.CENTER);profile.setOnClickListener(v->Navigator.open(this,"profile"));head.addView(profile,new LinearLayout.LayoutParams(Ui.dp(this,40),Ui.dp(this,40)));root.addView(head);
  LinearLayout content=Ui.v(this);content.setPadding(Ui.dp(this,16),Ui.dp(this,14),Ui.dp(this,16),Ui.dp(this,18));com.google.android.material.card.MaterialCardView hero=Ui.card(this);hero.setCardBackgroundColor(Constants.BLUE);LinearLayout hi=Ui.v(this);hi.setPadding(Ui.dp(this,18),Ui.dp(this,18),Ui.dp(this,18),Ui.dp(this,18));JSONObject h=home==null?null:home.optJSONObject("hero");hi.addView(Ui.text(this,h==null?"SCHOOLOS":h.optString("eyebrow","SCHOOLOS"),9,0xFFDDE4FF,true));hi.addView(Ui.text(this,h==null?"Your school workspace":h.optString("title","Your school workspace"),23,0xFFFFFFFF,true));hi.addView(Ui.text(this,h==null?"Native Android":h.optString("subtitle","Native Android"),11,0xFFE7EBFF,false));hero.addView(hi);content.addView(hero);content.addView(Ui.gap(this,14));content.addView(Ui.text(this,"SchoolOS Modules",18,Constants.TEXT,true));content.addView(Ui.text(this,"Every module below is a native Android screen.",10,Constants.MUTED,false));RecyclerView list=new RecyclerView(this);list.setLayoutManager(new LinearLayoutManager(this));list.setNestedScrollingEnabled(false);list.setAdapter(new Adapter(this,FeatureRegistry.forRole(role)));content.addView(list);content.addView(Ui.gap(this,12));com.google.android.material.button.MaterialButton logout=Ui.button(this,"Sign Out",0xFFFFFFFF,0xFFB43646);logout.setOnClickListener(v->io.execute(()->{try{api.post("logout",new JSONObject());}catch(Exception ignored){}api.store().clear();runOnUiThread(()->{startActivity(new Intent(this,LoginActivity.class));finishAffinity();});}));content.addView(logout);ScrollView scroll=new ScrollView(this);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));setContentView(root);}
 static final class Adapter extends RecyclerView.Adapter<Adapter.H>{private final HomeActivity a;private final List<String[]> rows;Adapter(HomeActivity x,List<String[]>r){a=x;rows=r;}public H onCreateViewHolder(ViewGroup p,int t){com.google.android.material.card.MaterialCardView c=Ui.card(a);LinearLayout in=Ui.v(a);in.setPadding(Ui.dp(a,14),Ui.dp(a,12),Ui.dp(a,14),Ui.dp(a,12));c.addView(in);RecyclerView.LayoutParams lp=new RecyclerView.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);lp.setMargins(0,Ui.dp(a,8),0,0);c.setLayoutParams(lp);return new H(c,in);}public void onBindViewHolder(H h,int pos){String[]r=rows.get(pos);h.in.removeAllViews();h.in.addView(Ui.text(a,r[1],14,Constants.TEXT,true));h.in.addView(Ui.text(a,r[2]+" · Native screen",10,Constants.MUTED,false));h.itemView.setOnClickListener(v->Navigator.open(a,r[0]));}public int getItemCount(){return rows.size();}static final class H extends RecyclerView.ViewHolder{LinearLayout in;H(View v,LinearLayout i){super(v);in=i;}}}
}