plugins { id 'com.android.application' }

android {
    namespace 'com.schooloss.nativepreview'
    compileSdk 35

    signingConfigs {
        preview {
            storeFile rootProject.file('schoolos-stable-debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
            enableV1Signing true
            enableV2Signing true
        }
    }

    defaultConfig {
        applicationId 'com.schooloss.nativepreview'
        minSdk 24
        targetSdk 35
        versionCode 1001001
        versionName '1.0.1-ui-preview'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.preview
            applicationIdSuffix ''
            versionNameSuffix ''
        }
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.preview
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
