plugins { id 'com.android.application' }

configurations.configureEach {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.webkit:webkit:1.12.1'
    implementation 'com.google.firebase:firebase-messaging:23.4.1'
}

android {
    namespace 'com.schooloss.mobile'
    compileSdk 35

    signingConfigs {
        debug {
            storeFile rootProject.file('schoolos-stable-debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    defaultConfig {
        applicationId 'com.schooloss.mobile'
        minSdk 24
        targetSdk 35
        versionCode 3010005
        versionName '3.1.5'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
        debug {
            signingConfig signingConfigs.debug
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
