package com.schooloss.fullnative.feature.common;
import android.content.*;import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.recyclerview.widget.*;import androidx.swiperefreshlayout.widget.SwipeRefreshLayout;import com.schooloss.fullnative.core.*;import com.schooloss.fullnative.feature.attendance.AttendanceRegisterActivity;import com.schooloss.fullnative.feature.messages.ConversationActivity;import com.schooloss.fullnative.feature.sfh.SfhDetailActivity;import com.schooloss.fullnative.feature.gallery.GalleryAlbumActivity;import com.schooloss.fullnative.feature.results.ResultDetailActivity;import org.json.*;
public class FeatureActivity extends BaseActivity {
 protected String feature;private RecyclerView list;private Adapter adapter;private SwipeRefreshLayout swipe;private TextView title,subtitle,empty;
 @Override protected void onCreate(Bundle b){super.onCreate(b);feature=getIntent().getStringExtra("feature");if(feature==null)feature="profile";build();load();}
 private void build(){LinearLayout root=Ui.v(this);root.setBackgroundColor(Constants.BG);LinearLayout bar=Ui.h(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(Ui.dp(this,14),Ui.dp(this,10),Ui.dp(this,14),Ui.dp(this,10));bar.setBackgroundColor(0xFFFFFFFF);TextView back=Ui.text(this,"‹",28,Constants.TEXT,true);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());bar.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,42),Ui.dp(this,42)));LinearLayout bc=Ui.v(this);title=Ui.text(this,Ui.pretty(feature),18,Constants.TEXT,true);subtitle=Ui.text(this,"Native SchoolOS module",10,Constants.MUTED,false);bc.addView(title);bc.addView(subtitle);bar.addView(bc,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(bar);swipe=new SwipeRefreshLayout(this);LinearLayout body=Ui.v(this);body.setPadding(Ui.dp(this,14),Ui.dp(this,8),Ui.dp(this,14),Ui.dp(this,16));empty=Ui.text(this,"",12,Constants.MUTED,false);empty.setGravity(Gravity.CENTER);empty.setPadding(0,Ui.dp(this,18),0,Ui.dp(this,10));body.addView(empty);list=new RecyclerView(this);list.setLayoutManager(new LinearLayoutManager(this));adapter=new Adapter(this);list.setAdapter(adapter);body.addView(list);swipe.addView(body);swipe.setOnRefreshListener(this::load);root.addView(swipe,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));setContentView(root);}
 protected void load(){swipe.setRefreshing(true);io.execute(()->{try{JSONObject r=api.module(feature);JSONObject d=r.optJSONObject("data");runOnUiThread(()->show(d));}catch(Exception e){runOnUiThread(()->{swipe.setRefreshing(false);error("Could not load "+Ui.pretty(feature),e,this::load);});}});}
 protected void show(JSONObject d){swipe.setRefreshing(false);if(d==null)d=new JSONObject();title.setText(d.optString("title",Ui.pretty(feature)));subtitle.setText(d.optString("subtitle","Native SchoolOS module"));JSONArray rows=d.optJSONArray("rows");adapter.set(rows);empty.setText(rows==null||rows.length()==0?"No records are available for this school context.":"");afterData(d);}
 protected void afterData(JSONObject d){}
 protected void openRow(JSONObject r){String type=r.optString("type","");int id=r.optInt("id",0);Intent i=null;if("attendance_context".equals(type)){i=new Intent(this,AttendanceRegisterActivity.class);i.putExtra("class_id",r.optInt("class_id",id));i.putExtra("section_id",r.optInt("section_id",0));}else if("conversation".equals(type)){i=new Intent(this,ConversationActivity.class);i.putExtra("id",id);}else if(type.startsWith("sfh_")){i=new Intent(this,SfhDetailActivity.class);i.putExtra("id",id);i.putExtra("type",type);}else if("gallery_album".equals(type)){i=new Intent(this,GalleryAlbumActivity.class);i.putExtra("id",id);}else if("result_term".equals(type)||"result_exam".equals(type)){i=new Intent(this,ResultDetailActivity.class);i.putExtra("id",id);i.putExtra("kind","result_exam".equals(type)?"exam":"term");}else if(!r.optString("module","").isEmpty()){Navigator.open(this,r.optString("module"));return;}else if(id>0){i=new Intent(this,EntityDetailActivity.class);i.putExtra("type",type.isEmpty()?feature:type);i.putExtra("id",id);}if(i!=null)startActivity(i);}
 static final class Adapter extends RecyclerView.Adapter<Adapter.H>{private final FeatureActivity a;private JSONArray rows=new JSONArray();Adapter(FeatureActivity x){a=x;}void set(JSONArray r){rows=r==null?new JSONArray():r;notifyDataSetChanged();}public H onCreateViewHolder(ViewGroup p,int t){com.google.android.material.card.MaterialCardView c=Ui.card(a);LinearLayout in=Ui.v(a);in.setPadding(Ui.dp(a,14),Ui.dp(a,12),Ui.dp(a,14),Ui.dp(a,12));c.addView(in);RecyclerView.LayoutParams lp=new RecyclerView.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);lp.setMargins(0,Ui.dp(a,7),0,0);c.setLayoutParams(lp);return new H(c,in);}public void onBindViewHolder(H h,int p){JSONObject r=rows.optJSONObject(p);if(r==null)return;h.in.removeAllViews();h.in.addView(Ui.text(a,r.optString("title","Record"),13,Constants.TEXT,true));if(!r.optString("subtitle","").isEmpty())h.in.addView(Ui.text(a,r.optString("subtitle"),10,Constants.MUTED,false));if(!r.optString("meta","").isEmpty())h.in.addView(Ui.text(a,r.optString("meta"),9,Constants.BLUE,true));h.itemView.setOnClickListener(v->a.openRow(r));}public int getItemCount(){return rows.length();}static final class H extends RecyclerView.ViewHolder{LinearLayout in;H(View v,LinearLayout i){super(v);in=i;}}}
}